services:
#    sfworker_image.example:
#        class: Sfworker\ImageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Sfworker\ImageBundle\Manager\Image:
        public: false

    im:
        alias: Sfworker\ImageBundle\Manager\Image