services:
#    sfworker_image.example:
#        class: Hnc\ImageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Hnc\ImageBundle\Manager\Image:
        public: false

    im:
        alias: Hnc\ImageBundle\Manager\Image